# === Cornell MAE Portfolio — Minimal _config.yml (starter) ===
# Replace the angle-bracket placeholders below before publishing.
# For a "project site" under your account (recommended):
#   url: "https://<YOUR_GITHUB_USERNAME>.github.io"   # NO trailing slash
#   base_url: "/<YOUR_REPO_NAME>"                      # leading slash, no trailing
#
# For an org-classroom repo (e.g., cornell-mae-ug.github.io/<repo>), set url to that org.
# The template supports color schemes via `skin:` (e.g., aqua, crimson, graphite).
title: "Ishan — Engineering Portfolio"
name: "Ishan"
email: your.email@domain.com
url: "https://ishanr254.github.io"
base_url: "/portfolio-ishanr254"
skin: aqua

# Collections for projects (the template already defines these in layouts)
collections:
  projects:
    output: true

# Build options
markdown: kramdown
kramdown:
  input: GFM

# Social (optional)
github_username: <YOUR_GITHUB_USERNAME>
linkedin: <YOUR_LINKEDIN_SLUG>

# Navigation labels (optional)
nav_links:
  - title: Projects
    url: /projects/
  - title: CV
    url: /cv/
  - title: Contact
    url: /#contact
